### ISSUE TITLE
styles.css

### ISSUE THREAD

**Issue by Mikevd6** [Mikevd6/Huiswerk-loops-and-arrays#11]
```css
.sold-count {
    color: green;
}
.stock-count {
    color: blue;
}
.remaining-count {
    color: red;
}
```
